# Autogenerated wrapper script for pppack_jll for x86_64-w64-mingw32-libgfortran5
export pppack

using CompilerSupportLibraries_jll
JLLWrappers.@generate_wrapper_header("pppack")
JLLWrappers.@declare_library_product(pppack, "libpppack.dll")
function __init__()
    JLLWrappers.@generate_init_header(CompilerSupportLibraries_jll)
    JLLWrappers.@init_library_product(
        pppack,
        "bin\\libpppack.dll",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@generate_init_footer()
end  # __init__()
